### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by targos** [cheminfo/eslint-config-cheminfo-typescript#1]
Dependencies:

- `eslint-plugin-typescript`
- `typescript-eslint-parser`

Config:

```yml
extends: cheminfo
parser: typescript-eslint-parser
parserOptions:
  sourceType: module
plugins:
  - typescript
settings:
  import/resolver:
    node:
      extensions:
        - '.ts' # maybe add ".js" just in case
rules:
  typescript/interface-name-prefix: [2, always] # Interfaces must have "I" prefix
  typescript/explicit-function-return-type: 0 # Let TS infer the types
  typescript/no-unused-vars: 2 # Needed for compatibility with ESLint rule
  no-undef: off  # TypeScript flags it already
  valid-jsdoc: off   # todo re-enable with different settings. for example, return type is not necessary

```
